/// Flutter icons AppIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcon
///      fonts:
///       - asset: fonts/AppIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcon {
  AppIcon._();

  static const _kFontFam = 'AppIcon';
  static const _kFontPkg = null;

  static const IconData bow_tie = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData judo = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mortarboard = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security_on = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entrance = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tie = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData working_at_home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmet = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
